### ISSUE TITLE
Invalid framework build

### ISSUE THREAD

**Issue by iamjason** [Ziggeo/iOS-Client-SDK#1]
I've getting the following error messages from Apple when submitting to my app with the Ziggeo.framework included:

```
The executable 'Payload/MyApp.app/Frameworks/Ziggeo.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."

Unsupported Architectures. The executable for MyApp.app/Frameworks/Ziggeo.framework contains unsupported architectures '[x86_64, i386]'."

"Invalid Segment Alignment. The app binary at 'MyApp.app/Frameworks/Ziggeo.framework/Ziggeo' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

"The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

```

It seems that rebuilding the framework with the latest version of XCode would fix the issue.

Thanks!

**Comment by alexyats** [comment]
Hi Jason,

try to add this script as a custom building step to remove unwanted architectures. Here is detailed description of the issue and the workaround: http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

```
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
    FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
    FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
    echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

    EXTRACTED_ARCHS=()

    for ARCH in $ARCHS
    do
        echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
        lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
        EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
    done

    echo "Merging extracted architectures: ${ARCHS}"
    lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
    rm "${EXTRACTED_ARCHS[@]}"

    echo "Replacing original executable with thinned version"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```

**Comment by iamjason** [comment]
Thanks for the quick response!

I'm currently having a bit of trouble with a direct copy & paste of the script.  It's seems to be trying to remove files that don't exist.  Here is one example of the error (although multiple libraries have the same error):

``` Executable is /.../Build/Products/Debug-iphoneos/MyApp.app/Frameworks/Alamofire.framework/Alamofire
Extracting arm64 from Alamofire
fatal error: lipo: input file (/.../Build/Products/Debug-iphoneos/MyApp.app/Frameworks/Alamofire.framework/Alamofire) must be a fat file when the -extract option is specified
Merging extracted architectures: arm64
fatal error: lipo: can't open input file: /.../Build/Products/Debug-iphoneos/MyApp.app/Frameworks/Alamofire.framework/Alamofire-arm64 (No such file or directory)
rm: /.../Build/Products/Debug-iphoneos/MyApp.app/Frameworks/Alamofire.framework/Alamofire-arm64: No such file or directory
Replacing original executable with thinned version
mv: rename /.../Build/Products/Debug-iphoneos/MyApp.app/Frameworks/Alamofire.framework/Alamofire-merged to /.../Build/Products/Debug-iphoneos/MyApp.app/Frameworks/Alamofire.framework/Alamofire: No such file or directory ```

I've also discovered that the framework isn't bitcode compatible.  This will require the framework to be rebuilt even if I can get the above script working.  Here is the error message from XCode:

``` ld: '.../Ziggeo.framework/Ziggeo' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64  ```

So ideally, Ziggeo's Client SDK would have separate libraries for each platform.  For example, this is Alamofire's (https://github.com/Alamofire/Alamofire) setup:
<img width="193" alt="alamofire" src="https://cloud.githubusercontent.com/assets/442302/12043046/c978302c-ae4e-11e5-96bb-5692cd231cad.png">

This would prevent using a build script that future versions of XCode could potentially break.

Thanks!

**Comment by alexyats** [comment]
Hi Jason,

thank you for detailed report, we will check the bitcode issue on latest xcode version and will let you know

**Comment by alexyats** [comment]
Hi Jason, we've updated framework binaries, so could you please check it again?

**Comment by iamjason** [comment]
After trying both frameworks, I'm still having issues.  The universal framework built correctly for the simulator (the ios version was missing the slice? but, wouldn't compile for the simulator).

So, in order to narrow down the error, I replaced the bundle identifier & entitlements in the 'AdvancedTestApp' demo with valid info and archived successfully...  Unfortunately, when submitting the archived demo app to Apple, the same error message was returned:

<img width="580" alt="screenshot 2016-01-10 14 35 02" src="https://cloud.githubusercontent.com/assets/442302/12223502/7502fc0e-b7a7-11e5-87ed-dd90ddb5fadd.png">

I'm more than happy to keep debugging this with you, but, at this point, I'm really only looking for the ZiggeoPlayer... So, if there is a utility class that you could release that constructs the urls (that gets passed the ziggeo id & video id).  That's really all I need at the moment.

Thanks!

**Comment by alexyats** [comment]
Hi Jason, please contact Ziggeo Support Team here: https://ziggeo.zendesk.com/hc/en-us/requests/new

They will help you to generate the URLs

**Comment by iamjason** [comment]
Thanks, let me know if you'd like any help debugging this in the future... but, for the time being, we're not including the Ziggeo Client framework.

**Comment by alexyats** [comment]
Hi Jason, sorry for delay, could you please try one more framework version (attached)
[Ziggeo.framework.zip](https://github.com/Ziggeo/iOS-Client-SDK/files/99993/Ziggeo.framework.zip)
?

**Comment by girishPC** [comment]
I am getting this error after using the new framework 

2017-02-28 23:47:15.953 OptimizeVideo[5941:2180321] file /var/mobile/Containers/Data/Application/DF22BC6E-904B-4AF5-9504-6FD92FC2DCC7/Documents/509998635.mp4 captured
2017-02-28 23:47:15.983 OptimizeVideo[5941:2180321] foreground request
2017-02-28 23:47:15.984 OptimizeVideo[5941:2180321] request dump: ---REQUEST------------------
URL: https://embed.ziggeo.com/v1/applications/59fe26acd566f8bcc70f816261b7a787/videos?flash_recording=true
METHOD: POST
Content-Type: application/x-www-form-urlencoded
Content-Length: 0
BODY: 
----------------------------
2017-02-28 23:47:17.211 OptimizeVideo[5941:2181006] video created with error = Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}, response = (null)

**Comment by iamjason** [comment]
@girishPC This looks like a runtime error, no?  I was having an error when submitting my application.  So, I'm not sure if this thread is applicable to your issue.  I would suggest you start a new issue with the Ziggeo team.
