### ISSUE TITLE
iOS ZiggeoRecorder2 (beta) Capture duration limit?

### ISSUE THREAD

**Issue by ClipixIOS** [Ziggeo/iOS-Client-SDK#19]
Hello,
For iOS sdk, does  ZiggeoRecorder2 (beta) supports duration limit as ZiggeoRecorder?
I couldn't find anything about it on github page, maybe using extraArgsForCreateVideo value?
can you please help me
Thanks

**Comment by alexyats** [comment]
Hello, it doesn't support it for now, but will be added soon

**Comment by ClipixIOS** [comment]
Okay then I need to ask this
in new recorder we can sent "extraArgsForCreateVideo" for videp
is there any way that I can do it on old recorder ? Specifically effect_profile and key values?

**Comment by alexyats** [comment]
extra args are not implemented on old recorder, but we can add them if needed

**Comment by ClipixIOS** [comment]
I need to record video with time limit and also I need to be able to sent extra arguments.
So if it is possible add time limit to recorder version 2 or add arguments to recorder version 1
thank you

**Comment by alexyats** [comment]
both options are added
