### ISSUE TITLE
Upload Problems

### ISSUE THREAD

**Issue by ClipixIOS** [Ziggeo/iOS-Client-SDK#22]
I did everything on sdk documentation but when I try to upload it to app store I am getting this
Can you help me
<img width="745" alt="screen shot 2018-02-04 at 12 49 33" src="https://user-images.githubusercontent.com/12850507/35780494-432e4c54-09aa-11e8-9013-c3201395a42e.png">

**Comment by alexyats** [comment]
it seems you use Universal framework instead of Release one. Remove the Ziggeo.framework from your application and add it from `iOS-Client-SDK/Ziggeo/Output/Release` directory
