### ISSUE TITLE
Uncaught exception 'NSInternalInconsistencyException'

### ISSUE THREAD

**Issue by abinop** [Ziggeo/iOS-Client-SDK#3]
Hello,
when I run the CustomUITestApp project from the samples I get 

> **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'accessing _cachedSystemAnimationFence requires the main thread'

after I press the "Stop and upload button".

**Comment by alexyats** [comment]
Hello, we are fixing it now. What is your iOS version?

**Comment by IOSAppDev5** [comment]
Its crashing in 9.3.5 IOS version Iphone also
