### ISSUE TITLE
i could not solve this error .can anyone help me?

### ISSUE THREAD

**Issue by erkrujjawal786** [Ziggeo/iOS-Client-SDK#38]

**Comment by erkrujjawal786** [comment]
fatal error: 'Ziggeo/Ziggeo.h' file not found

**Comment by alexyats** [comment]
Hi, please ensure you have Ziggeo.framework added into the root of your project. Or, If you use it from another directory, ensure you have Framework and Header Search path specified at your project settings. But usually it is easier to just drop framework into the root directory of your project and add it to the Linked libraries and Embedded Binaries sections

**Comment by katolykdev** [comment]
@erkrujjawal786 
Did the previous comment help?
