### ISSUE TITLE
how to setup for EU servers 

### ISSUE THREAD

**Issue by IOSAppDev5** [Ziggeo/iOS-Client-SDK#4]
HI 
We are using the objective-c sdk in swift project with the latest Application token: xxxxxxxxxx, I am not able to upload the videos  from the sdk, for the reference of sdk version I have attached the info.plist of the sdk and screenshot. The current IOS sdk is pointing to this url "https://embed.ziggeo.com/v1/applications/xxxxxxxxxx/videos?flash_recording=true" while debugging.
getting this response
 
METHOD: POST
Content-Type: application/x-www-form-urlencoded
Content-Length: 0
BODY:
----------------------------
 video created with error = Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}, response = (null)

is there help will be from following parameters 

@property (strong, nonatomic) NSString *server_api_url;
@property (strong, nonatomic) NSString *cdn_api_url;

for switching server URL

**Comment by alexyats** [comment]
Hi, do you use r1-prefixed (EU) app token?

**Comment by alexyats** [comment]
Hi, we are working on the issue and will update the objective-C sdk ASAP

**Comment by alexyats** [comment]
Hi, please check the latest SDK version
