### ISSUE TITLE
Pod name is too generic

### ISSUE THREAD

**Issue by sryze** [Ziggeo/iOS-Client-SDK#86]
`iOS-Client-SDK` is a pretty generic name for a CocoaPods library. Perhaps it would be better to add "Ziggeo" to the name to avoid possible name collision with other vendor's pods. It would also make it a little easier to browser the source code inside the `Pods/` directory after installed.

**Comment by katolykdev** [comment]
Pod name was changed to `ZiggeoMediaSDK`.
