### ISSUE TITLE
ld: building for iOS Simulator, but linking in dylib built for iOS, file '.../Pods/iOS-Client-SDK/Output/SelfieSegmentation.framework/SelfieSegmentation' for architecture arm64

### ISSUE THREAD

**Issue by sryze** [Ziggeo/iOS-Client-SDK#87]
When you build and run Ziggeo SDK on an M1 Mac inside the iOS Simulator, linker complains about architecture mismatch:

```
ld: building for iOS Simulator, but linking in dylib built for iOS, file '.../Pods/iOS-Client-SDK/Output/SelfieSegmentation.framework/SelfieSegmentation' for architecture arm64
```

Per Apple's technical note at https://developer.apple.com/documentation/technotes/tn3117-resolving-build-errors-for-apple-silicon the vendor of SelfieSegmentation should recompile their framework:

> Since your app expects this library to be available in builds targeting the simulator, rebuild the library as an XCFramework with support for the simulator on Apple silicon. To learn how to build an XCFramework, see [Create an XCFramework](https://help.apple.com/xcode/mac/current/#/dev544efab96). If the library is from a vendor, contact the vendor for an updated XCFramework supporting Apple silicon. If an update isn’t available, remove the dependency from your app.
>
> Note
>
> A pre-compiled library must be built as an XCFramework to separate the device and simulator builds. Combining architectures for iOS, watchOS, or tvOS and their respective simulators into a single binary file is not supported.
>
> If you’re developing a watchOS app, all XCFrameworks for your watchOS app must contain arm64 or x86_64 libraries built specifically for the watchOS simulator. If you need to test your watchOS app specifically using the i386 architecture with the watchOS simulator, use an Intel-based Mac.

A common suggestion for fixing this issue is to set `EXCLUDED_ARCHS` to `arm64` in a project's build settings for the simulator target, but this makes your iOS app run non-natively under Rosetta (as x86 code) when launching on the simulator and causes a bunch of other issues.

**Update:**

It seems that the same needs to be done for ZIggeo.framework.

**Comment by katolykdev** [comment]
It was fixed on 1.1.38.
